import { pgTable, text, boolean, timestamp, uuid, pgEnum, integer, foreignKey } from 'drizzle-orm/pg-core';
import { relations } from "drizzle-orm";

export const userRoleEnum = pgEnum('user_role', [
  'MEMBER', 
  'USER',
  'ADMIN',
  'SUPER_ADMIN',
  'PASTOR',
  'PASTORS_WIFE',
  'CHILDREN_LEADER',
  'CHOIRMASTER',
  'CHORISTER',
  'SOUND_EQUIPMENT',
  'SECURITY',
  'USHERS_LEADER',
  'USHER',
  'SUNDAY_SCHOOL_TEACHER',
  'CELL_LEADER',
  'PRAYER_TEAM',
  'FINANCE_TEAM',
  'TECH_TEAM',
  'DECOR_TEAM',
  'EVANGELISM_TEAM',
]);

export const organizations = pgTable('organizations', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: text('name').notNull(),
  slug: text('slug').notNull().unique(),
  description: text('description'),
  logoUrl: text('logo_url'),
  faviconUrl: text('favicon_url'),
  colors: text('colors').default('{"primary":"#3b82f6","secondary":"#ffffff","accent":"#10b981"}'),
  fonts: text('fonts').default('{"heading":"Inter","body":"Inter"}'),
  churchName: text('church_name'),
  churchAddress: text('church_address'),
  churchCity: text('church_city'),
  churchState: text('church_state'),
  churchCountry: text('church_country'),
  churchZipCode: text('church_zip_code'),
  churchPhone: text('church_phone'),
  churchEmail: text('church_email'),
  churchLatitude: text('church_latitude'),
  churchLongitude: text('church_longitude'),
  serviceTimes: text('service_times').default('{"sunday":"7:00 AM & 9:00 AM","wednesday":"6:00 PM","friday":"7:00 PM"}'),
  youtubeUrl: text('youtube_url'),
  instagramUrl: text('instagram_url'),
  facebookUrl: text('facebook_url'),
  twitterUrl: text('twitter_url'),
  isActive: boolean('is_active').default(true).notNull(),
  approvalStatus: text('approval_status').default('pending').notNull(), // 'pending', 'approved', 'rejected'
  rejectionReason: text('rejection_reason'),
  approvedAt: timestamp('approved_at'),
  approvedBy: uuid('approved_by').references(() => users.id),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

export const users = pgTable('users', {
  id: uuid('id').primaryKey().defaultRandom(),
  email: text('email').notNull().unique(),
  passwordHash: text('password_hash').notNull(),
  firstName: text('first_name').notNull(),
  lastName: text('last_name').notNull(),
  phone: text('phone'),
  address: text('address'),
  profileImage: text('profile_image'),
  houseFellowship: text('house_fellowship'),
  houseCellLocation: text('house_cell_location'),
  houseCellId: integer('house_cell_id'),
  parish: text('parish'),
  career: text('career'),
  stateOfOrigin: text('state_of_origin'),
  birthday: timestamp('birthday'),
  twitterHandle: text('twitter_handle'),
  instagramHandle: text('instagram_handle'),
  facebookHandle: text('facebook_handle'),
  linkedinHandle: text('linkedin_handle'),
  isAdmin: boolean('is_admin').default(false).notNull(),
  isSuperAdmin: boolean('is_super_admin').default(false).notNull(),
  organizationId: uuid('organization_id').references(() => organizations.id),
  isVerified: boolean('is_verified').default(false).notNull(),
  verificationToken: text('verification_token'),
  verificationTokenExpires: timestamp('verification_token_expires'),
  resetPasswordToken: text('reset_password_token'),
  resetPasswordExpires: timestamp('reset_password_expires'),
  twoFactorEnabled: boolean('two_factor_enabled').default(false),
  twoFactorSecret: text('two_factor_secret'),
  twoFactorBackupCodes: text('two_factor_backup_codes').array(),
  role: userRoleEnum('role').default('MEMBER').notNull(),
  preferredLanguage: text('preferred_language').default('en'),
  timezone: text('timezone').default('UTC'),
  currency: text('currency').default('USD'),
  lastContactedAt: timestamp('last_contacted_at'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;
